feat(scoring): Add a scoring mechanism
LuminousSpike/pocket-aquarium pull request #10
Opened 2024-09-21 10:41 UTC by sam-mathews

This commit adds a basic scoring mechanism. The game starts with a preset bank balance and is decreased as food is purchased. If there is insufficient funds for food, the fish cannot be fed. If a coin is collected from a fish, it increases the bank balance accordingly.

2024-09-21 11:57 UTC, LuminousSpike requested changes
Just needs the VRAM corruption issue sorted out.

2024-09-21 11:57 UTC, LuminousSpike commented on src/score.c
The use of the string drawing here means we're running out of VRAM.
![image](https://github.com/user-attachments/assets/6ec2168e-1417-41f8-9766-d1e0e2bae9fa)
![image](https://github.com/user-attachments/assets/00079369-32fc-4811-85d8-475da6fc5cc4)

This is how it should look like normally
![image](https://github.com/user-attachments/assets/a85183e9-a531-48fd-808f-e4c1e20fb557)
![image](https://github.com/user-attachments/assets/19b1e3a0-4ac2-43c5-8bc4-d98224950a8b)

What we'll need to do is either handle drawing strings ourselves with our own bitmap font, or look into some other way.

2024-09-22 00:46 UTC, LuminousSpike approved these changes
The graphical issues have been resolved. Awesome work! Approved.

2024-09-22 02:55 UTC, sam-mathews commented
Will need some more tidying, but good to get a stick in the ground.

2024-09-22 02:55 UTC, merged